name: Slack Notifications

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  notify-slack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send Slack Notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "Push to the main branch detected in the GitHub repository."
          }' $SLACK_WEBHOOK_URL
